version: '3.8'

services:
  wordpress:
    image: wordpress:php8.2-apache
    container_name: voseda_wp
    restart: unless-stopped
    ports:
      - "${WORDPRESS_PORT:-8080}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-false}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:${WORDPRESS_PORT:-8080}');
        define('WP_SITEURL', 'http://localhost:${WORDPRESS_PORT:-8080}');
    volumes:
      # Solo montamos wp-content para persistir temas, plugins y uploads
      - ./wp-content:/var/www/html/wp-content:delegated
      # Configuración PHP personalizada
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - voseda_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mariadb:10.6
    container_name: voseda_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      # Volumen nombrado para la base de datos (más eficiente en Windows)
      - db_data:/var/lib/mysql
    networks:
      - voseda_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # Configuración para mejorar rendimiento en Windows
    command: >
      --max_allowed_packet=256M
      --innodb_buffer_pool_size=512M
      --innodb_log_file_size=128M

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: voseda_pma
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 128M
    depends_on:
      db:
        condition: service_healthy
    networks:
      - voseda_network

networks:
  voseda_network:
    driver: bridge

volumes:
  db_data:
    driver: local